"""NexaPy JavaScript Client SDK Generator."""

import json
from pathlib import Path
from nexapy import __version__


def generate_javascript_sdk(
    output_dir: Path,
    base_url: str = "http://localhost:8000",
    ai_path: str = "/ai/chat",
) -> None:
    """Generate vanilla ES6 JavaScript NexaPyClient SDK (`client.js`)."""
    output_dir.mkdir(parents=True, exist_ok=True)
    clean_base_url_json = json.dumps(base_url.rstrip("/"))
    clean_ai_path_json = json.dumps("/" + ai_path.lstrip("/"))

    client_js = f'''/**
 * NexaPy JavaScript Client SDK (v{__version__})
 * Auto-generated by NexaPy Framework CLI
 */
export class NexaPyClient {{
  constructor({{ baseURL = {clean_base_url_json}, timeout = 30000 }} = {{}}) {{
    this.baseURL = baseURL.replace(/\\/+$/, "");
    this.timeout = timeout;
    this.aiPath = {clean_ai_path_json};
  }}

  async chat(prompt, {{ provider = null, reasoning = null, temperature = null, maxTokens = null, timeout = null }} = {{}}) {{
    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {{
      throw new Error("NexaPyClient: prompt parameter is required and cannot be empty.");
    }}

    const payload = {{ prompt }};
    if (provider) payload.provider = provider;
    if (reasoning) payload.reasoning = reasoning;
    if (temperature !== null && temperature !== undefined) payload.temperature = temperature;
    if (maxTokens !== null && maxTokens !== undefined) payload.max_tokens = maxTokens;

    const reqTimeout = timeout !== null && timeout !== undefined ? timeout : this.timeout;
    const controller = typeof AbortController !== "undefined" ? new AbortController() : null;
    const timer = controller && reqTimeout > 0 ? setTimeout(() => controller.abort(), reqTimeout) : null;

    try {{
      const response = await fetch(`${{this.baseURL}}${{this.aiPath}}`, {{
        method: "POST",
        headers: {{
          "Content-Type": "application/json",
        }},
        body: JSON.stringify(payload),
        signal: controller ? controller.signal : undefined,
      }});

      let data;
      try {{
        data = await response.json();
      }} catch (_jsonErr) {{
        return {{
          text: "",
          provider: provider || "unknown",
          model: "unknown",
          success: false,
          error: `HTTP ${{response.status}} Invalid JSON Response`,
        }};
      }}

      if (!response.ok) {{
        return {{
          text: "",
          provider: provider || "unknown",
          model: "unknown",
          success: false,
          error: data.detail || data.error || `HTTP ${{response.status}} Error`,
        }};
      }}

      return {{
        text: data.text || "",
        provider: data.provider || "unknown",
        model: data.model || "unknown",
        success: data.success ?? true,
        error: data.error || null,
      }};
    }} catch (err) {{
      const errorMsg = err && err.name === "AbortError"
        ? `Request timed out after ${{reqTimeout}}ms`
        : (err && err.message ? err.message : "Network request failed");

      return {{
        text: "",
        provider: provider || "unknown",
        model: "unknown",
        success: false,
        error: errorMsg,
      }};
    }} finally {{
      if (timer) clearTimeout(timer);
    }}
  }}

  async generate(prompt, options = {{}}) {{
    return this.chat(prompt, options);
  }}
}}
'''
    (output_dir / "client.js").write_text(client_js, encoding="utf-8")
