"""NexaPy JavaScript Client SDK Generator."""

from pathlib import Path


def generate_javascript_sdk(output_dir: Path, base_url: str = "http://localhost:8000") -> None:
    """Generate vanilla ES6 JavaScript NexaPyClient SDK (`client.js`)."""
    output_dir.mkdir(parents=True, exist_ok=True)
    clean_base_url = base_url.rstrip("/")

    client_js = f'''/**
 * NexaPy JavaScript Client SDK (v0.2)
 * Auto-generated by NexaPy Framework CLI
 */
export class NexaPyClient {{
  constructor({{ baseURL = "{clean_base_url}" }} = {{}}) {{
    this.baseURL = baseURL.replace(/\\/+$/, "");
  }}

  async chat(prompt, {{ provider = null, reasoning = null, temperature = null, maxTokens = null }} = {{}}) {{
    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {{
      throw new Error("NexaPyClient: prompt parameter is required and cannot be empty.");
    }}

    const payload = {{ prompt }};
    if (provider) payload.provider = provider;
    if (reasoning) payload.reasoning = reasoning;
    if (temperature !== null && temperature !== undefined) payload.temperature = temperature;
    if (maxTokens !== null && maxTokens !== undefined) payload.max_tokens = maxTokens;

    const response = await fetch(`${{this.baseURL}}/ai/chat`, {{
      method: "POST",
      headers: {{
        "Content-Type": "application/json",
      }},
      body: JSON.stringify(payload),
    }});

    const data = await response.json();
    if (!response.ok) {{
      return {{
        text: "",
        provider: provider || "unknown",
        model: "unknown",
        success: false,
        error: data.detail || data.error || `HTTP ${{response.status}} Error`,
      }};
    }}

    return {{
      text: data.text || "",
      provider: data.provider || "unknown",
      model: data.model || "unknown",
      success: data.success ?? true,
      error: data.error || null,
    }};
  }}

  async generate(prompt, options = {{}}) {{
    return this.chat(prompt, options);
  }}
}}
'''
    (output_dir / "client.js").write_text(client_js, encoding="utf-8")
