"""NexaPy React Hook SDK Generator."""

from pathlib import Path
from nexapy import __version__
from .typescript import generate_typescript_sdk


def generate_react_sdk(
    output_dir: Path,
    base_url: str = "http://localhost:8000",
    ai_path: str = "/ai/chat",
) -> None:
    """Generate React Hook SDK (`react/useNexaPy.ts`, `react/index.ts`) alongside TypeScript client files."""
    # 1. Generate base TypeScript client files
    generate_typescript_sdk(output_dir, base_url=base_url, ai_path=ai_path)

    # 2. Generate React sub-directory
    react_dir = output_dir / "react"
    react_dir.mkdir(parents=True, exist_ok=True)

    use_nexapy_ts = f'''import {{ useState, useCallback }} from "react";
import {{ NexaPyClient }} from "../client";
import {{ AIResponse, AIChatOptions, NexaPyClientOptions }} from "../types";

/**
 * Options for useNexaPy React Hook (v{__version__})
 */
export interface UseNexaPyOptions extends NexaPyClientOptions {{
  client?: NexaPyClient;
}}

/**
 * Return type interface for useNexaPy hook
 */
export interface UseNexaPyReturn {{
  send: (prompt: string, options?: AIChatOptions) => Promise<AIResponse>;
  data: AIResponse | null;
  loading: boolean;
  error: string | null;
  reset: () => void;
}}

/**
 * NexaPy React Hook (useNexaPy)
 * Auto-generated by NexaPy Framework CLI
 *
 * Usage:
 *   const {{ send, data, loading, error }} = useNexaPy();
 *   await send("Hello NexaPy!");
 */
export function useNexaPy(options: UseNexaPyOptions = {{}}): UseNexaPyReturn {{
  const [client] = useState(() => options.client || new NexaPyClient(options));
  const [data, setData] = useState<AIResponse | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const reset = useCallback(() => {{
    setData(null);
    setLoading(false);
    setError(null);
  }}, []);

  const send = useCallback(
    async (prompt: string, chatOptions?: AIChatOptions): Promise<AIResponse> => {{
      setLoading(true);
      setError(null);
      try {{
        const res = await client.chat(prompt, chatOptions);
        setData(res);
        if (!res.success) {{
          setError(res.error);
        }}
        return res;
      }} catch (err: any) {{
        const errorMsg = err && err.message ? err.message : "Request failed";
        const failRes: AIResponse = {{
          text: "",
          provider: (chatOptions && chatOptions.provider) || "unknown",
          model: "unknown",
          success: false,
          error: errorMsg,
        }};
        setData(failRes);
        setError(errorMsg);
        return failRes;
      }} finally {{
        setLoading(false);
      }}
    }},
    [client]
  );

  return {{ send, data, loading, error, reset }};
}}
'''
    (react_dir / "useNexaPy.ts").write_text(use_nexapy_ts, encoding="utf-8")

    react_index_ts = '''export * from "./useNexaPy";
'''
    (react_dir / "index.ts").write_text(react_index_ts, encoding="utf-8")
