"""NexaPy TypeScript Client SDK Generator."""

from pathlib import Path


def generate_typescript_sdk(output_dir: Path, base_url: str = "http://localhost:8000") -> None:
    """Generate TypeScript NexaPyClient SDK (`client.ts`, `types.ts`, `index.ts`)."""
    output_dir.mkdir(parents=True, exist_ok=True)
    clean_base_url = base_url.rstrip("/")

    # 1. types.ts
    types_ts = '''/**
 * NexaPy TypeScript SDK Types
 * Auto-generated by NexaPy Framework CLI
 */
export interface AIResponse {
  text: string;
  provider: "freemodel" | "gemini" | string;
  model: string;
  success: boolean;
  error: string | null;
}

export interface AIChatOptions {
  provider?: "auto" | "freemodel" | "gemini";
  reasoning?: "low" | "medium" | "high";
  temperature?: number;
  maxTokens?: number;
}

export interface NexaPyClientOptions {
  baseURL?: string;
}
'''
    (output_dir / "types.ts").write_text(types_ts, encoding="utf-8")

    # 2. client.ts
    client_ts = f'''import {{ AIResponse, AIChatOptions, NexaPyClientOptions }} from "./types";

/**
 * NexaPy TypeScript Client SDK (v0.2)
 * Auto-generated by NexaPy Framework CLI
 */
export class NexaPyClient {{
  private baseURL: string;

  constructor(options: NexaPyClientOptions = {{}}) {{
    this.baseURL = (options.baseURL || "{clean_base_url}").replace(/\\/+$/, "");
  }}

  async chat(prompt: string, options: AIChatOptions = {{}}): Promise<AIResponse> {{
    if (!prompt || !prompt.trim()) {{
      throw new Error("NexaPyClient: prompt parameter is required and cannot be empty.");
    }}

    const payload: Record<string, unknown> = {{ prompt }};
    if (options.provider) payload.provider = options.provider;
    if (options.reasoning) payload.reasoning = options.reasoning;
    if (options.temperature !== undefined) payload.temperature = options.temperature;
    if (options.maxTokens !== undefined) payload.max_tokens = options.maxTokens;

    const response = await fetch(`${{this.baseURL}}/ai/chat`, {{
      method: "POST",
      headers: {{
        "Content-Type": "application/json",
      }},
      body: JSON.stringify(payload),
    }});

    const data = await response.json();
    if (!response.ok) {{
      return {{
        text: "",
        provider: options.provider || "unknown",
        model: "unknown",
        success: false,
        error: data.detail || data.error || `HTTP ${{response.status}} Error`,
      }};
    }}

    return {{
      text: data.text || "",
      provider: data.provider || "unknown",
      model: data.model || "unknown",
      success: data.success ?? true,
      error: data.error || null,
    }};
  }}

  async generate(prompt: string, options: AIChatOptions = {{}}): Promise<AIResponse> {{
    return this.chat(prompt, options);
  }}
}}
'''
    (output_dir / "client.ts").write_text(client_ts, encoding="utf-8")

    # 3. index.ts
    index_ts = '''export * from "./types";
export * from "./client";
'''
    (output_dir / "index.ts").write_text(index_ts, encoding="utf-8")
