"""NexaPy TypeScript Client SDK Generator."""

from pathlib import Path
from nexapy import __version__


def generate_typescript_sdk(
    output_dir: Path,
    base_url: str = "http://localhost:8000",
    ai_path: str = "/ai/chat",
) -> None:
    """Generate TypeScript NexaPyClient SDK (`client.ts`, `types.ts`, `index.ts`)."""
    output_dir.mkdir(parents=True, exist_ok=True)
    clean_base_url = base_url.rstrip("/")
    clean_ai_path = "/" + ai_path.lstrip("/")

    # 1. types.ts
    types_ts = f'''/**
 * NexaPy TypeScript SDK Types (v{__version__})
 * Auto-generated by NexaPy Framework CLI
 */
export type AIProvider = "freemodel" | "gemini" | "unknown" | (string & {{}});

export type AIProviderOption = "auto" | "freemodel" | "gemini";

export type AIReasoningOption = "low" | "medium" | "high";

export interface AIResponse {{
  text: string;
  provider: AIProvider;
  model: string;
  success: boolean;
  error: string | null;
}}

export interface AIChatOptions {{
  provider?: AIProviderOption;
  reasoning?: AIReasoningOption;
  temperature?: number;
  maxTokens?: number;
  timeout?: number;
}}

export interface NexaPyClientOptions {{
  baseURL?: string;
  timeout?: number;
}}
'''
    (output_dir / "types.ts").write_text(types_ts, encoding="utf-8")

    # 2. client.ts
    client_ts = f'''import {{ AIResponse, AIChatOptions, NexaPyClientOptions }} from "./types";

/**
 * NexaPy TypeScript Client SDK (v{__version__})
 * Auto-generated by NexaPy Framework CLI
 */
export class NexaPyClient {{
  private baseURL: string;
  private timeout: number;
  private aiPath: string;

  constructor(options: NexaPyClientOptions = {{}}) {{
    this.baseURL = (options.baseURL || "{clean_base_url}").replace(/\\/+$/, "");
    this.timeout = options.timeout !== undefined ? options.timeout : 30000;
    this.aiPath = "{clean_ai_path}";
  }}

  async chat(prompt: string, options: AIChatOptions = {{}}): Promise<AIResponse> {{
    if (!prompt || !prompt.trim()) {{
      throw new Error("NexaPyClient: prompt parameter is required and cannot be empty.");
    }}

    const payload: Record<string, unknown> = {{ prompt }};
    if (options.provider) payload.provider = options.provider;
    if (options.reasoning) payload.reasoning = options.reasoning;
    if (options.temperature !== undefined) payload.temperature = options.temperature;
    if (options.maxTokens !== undefined) payload.max_tokens = options.maxTokens;

    const reqTimeout = options.timeout !== undefined ? options.timeout : this.timeout;
    const controller = typeof AbortController !== "undefined" ? new AbortController() : null;
    const timer = controller && reqTimeout > 0 ? setTimeout(() => controller.abort(), reqTimeout) : null;

    try {{
      const response = await fetch(`${{this.baseURL}}${{this.aiPath}}`, {{
        method: "POST",
        headers: {{
          "Content-Type": "application/json",
        }},
        body: JSON.stringify(payload),
        signal: controller ? controller.signal : undefined,
      }});

      let data: any;
      try {{
        data = await response.json();
      }} catch (_jsonErr) {{
        return {{
          text: "",
          provider: options.provider || "unknown",
          model: "unknown",
          success: false,
          error: `HTTP ${{response.status}} Invalid JSON Response`,
        }};
      }}

      if (!response.ok) {{
        return {{
          text: "",
          provider: options.provider || "unknown",
          model: "unknown",
          success: false,
          error: data.detail || data.error || `HTTP ${{response.status}} Error`,
        }};
      }}

      return {{
        text: data.text || "",
        provider: data.provider || "unknown",
        model: data.model || "unknown",
        success: data.success ?? true,
        error: data.error || null,
      }};
    }} catch (err: any) {{
      const errorMsg = err && err.name === "AbortError"
        ? `Request timed out after ${{reqTimeout}}ms`
        : (err && err.message ? err.message : "Network request failed");

      return {{
        text: "",
        provider: options.provider || "unknown",
        model: "unknown",
        success: false,
        error: errorMsg,
      }};
    }} finally {{
      if (timer) clearTimeout(timer);
    }}
  }}

  async generate(prompt: string, options: AIChatOptions = {{}}): Promise<AIResponse> {{
    return this.chat(prompt, options);
  }}
}}
'''
    (output_dir / "client.ts").write_text(client_ts, encoding="utf-8")

    # 3. index.ts
    index_ts = '''export * from "./types";
export * from "./client";
'''
    (output_dir / "index.ts").write_text(index_ts, encoding="utf-8")
